OPTION(EQEMU_FETCH_MSVC_DEPENDENCIES_VCPKG "Automatically fetch vcpkg dependencies for MSCV" ON)
OPTION(EQEMU_FETCH_MSVC_DEPENDENCIES_PERL "Automatically fetch perl dependencies for MSCV" ON)

MARK_AS_ADVANCED(EQEMU_FETCH_MSVC_DEPENDENCIES_VCPKG)
MARK_AS_ADVANCED(EQEMU_FETCH_MSVC_DEPENDENCIES_PERL)

SET(EQEMU_MSVC_DEPENDENCIES_VCPKG_X86 "https://github.com/EQEmu/Server/releases/download/v1.2/vcpkg-export-x86.zip")
SET(EQEMU_MSVC_DEPENDENCIES_VCPKG_X64 "https://github.com/EQEmu/Server/releases/download/v1.2/vcpkg-export-x64.zip")
SET(EQEMU_MSVC_DEPENDENCIES_PERL_X86 "http://strawberryperl.com/download/5.24.4.1/strawberry-perl-5.24.4.1-32bit-portable.zip")
SET(EQEMU_MSVC_DEPENDENCIES_PERL_X64 "http://strawberryperl.com/download/5.24.4.1/strawberry-perl-5.24.4.1-64bit-portable.zip")
SET(EQEMU_MSVC_DEPENDENCIES_VCPKG_X86_ZIP "vcpkg-export-x86.zip")
SET(EQEMU_MSVC_DEPENDENCIES_VCPKG_X64_ZIP "vcpkg-export-x64.zip")
SET(EQEMU_MSVC_DEPENDENCIES_VCPKG_X86_DIR "vcpkg-export-x86")
SET(EQEMU_MSVC_DEPENDENCIES_VCPKG_X64_DIR "vcpkg-export-x64")
SET(EQEMU_MSVC_DEPENDENCIES_PERL_X86_ZIP "strawberry-perl-5.24.4.1-32bit-portable.zip")
SET(EQEMU_MSVC_DEPENDENCIES_PERL_X64_ZIP "strawberry-perl-5.24.4.1-64bit-portable.zip")
SET(EQEMU_MSVC_DEPENDENCIES_PERL_X86_DIR "x86")
SET(EQEMU_MSVC_DEPENDENCIES_PERL_X64_DIR "x64")

IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
	SET(EQEMU_VCPKG_URL ${EQEMU_MSVC_DEPENDENCIES_VCPKG_X64})
	SET(EQEMU_PERL_URL ${EQEMU_MSVC_DEPENDENCIES_PERL_X64})
	SET(EQEMU_VCPKG_ZIP ${EQEMU_MSVC_DEPENDENCIES_VCPKG_X64_ZIP})
	SET(EQEMU_VCPKG_DIR ${EQEMU_MSVC_DEPENDENCIES_VCPKG_X64_DIR})
	SET(EQEMU_PERL_ZIP ${EQEMU_MSVC_DEPENDENCIES_PERL_X64_ZIP})
	SET(EQEMU_PERL_DIR ${EQEMU_MSVC_DEPENDENCIES_PERL_X64_DIR})
ELSE()
	SET(EQEMU_VCPKG_URL ${EQEMU_MSVC_DEPENDENCIES_VCPKG_X86})
	SET(EQEMU_PERL_URL ${EQEMU_MSVC_DEPENDENCIES_PERL_X86})
	SET(EQEMU_VCPKG_ZIP ${EQEMU_MSVC_DEPENDENCIES_VCPKG_X86_ZIP})
	SET(EQEMU_VCPKG_DIR ${EQEMU_MSVC_DEPENDENCIES_VCPKG_X86_DIR})
	SET(EQEMU_PERL_ZIP ${EQEMU_MSVC_DEPENDENCIES_PERL_X86_ZIP})
	SET(EQEMU_PERL_DIR ${EQEMU_MSVC_DEPENDENCIES_PERL_X86_DIR})
ENDIF()

IF(EQEMU_FETCH_MSVC_DEPENDENCIES_VCPKG)
	MESSAGE(STATUS "Resolving vcpkg dependencies...")
	
	IF(NOT EXISTS ${PROJECT_SOURCE_DIR}/vcpkg/${EQEMU_VCPKG_ZIP})
		EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E make_directory ${PROJECT_SOURCE_DIR}/vcpkg)
		
		MESSAGE(STATUS "Downloading existing vcpkg dependencies from releases...")
		FILE(DOWNLOAD ${EQEMU_VCPKG_URL} ${PROJECT_SOURCE_DIR}/vcpkg/${EQEMU_VCPKG_ZIP} 
			SHOW_PROGRESS
			STATUS DOWNLOAD_STATUS)
			
		LIST(GET DOWNLOAD_STATUS 0 STATUS_CODE)
		IF(NOT STATUS_CODE EQUAL 0)
			MESSAGE(FATAL_ERROR "Was unable to download dependencies from ${EQEMU_VCPKG_URL}")
		ENDIF()
		
		MESSAGE(STATUS "Extracting files...")
		EXECUTE_PROCESS(
			COMMAND ${CMAKE_COMMAND} -E tar xzf ${PROJECT_SOURCE_DIR}/vcpkg/${EQEMU_VCPKG_ZIP}
			WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}/vcpkg
		)
	ENDIF()
	
	INCLUDE(${PROJECT_SOURCE_DIR}/vcpkg/${EQEMU_VCPKG_DIR}/scripts/buildsystems/vcpkg.cmake)
ENDIF()

IF(EQEMU_FETCH_MSVC_DEPENDENCIES_PERL)
	# Always use the portable Strawberry 5.24 that EQEmu ships for MSVC.
	# A winget/system install (5.38/5.40) is found first by FindPerlLibs, and
	# those headers call Perl_switch_locale_context. MSVC then looks for
	# __imp_Perl_switch_locale_context, which Strawberry's MinGW import
	# library does not provide. That produces LNK2019 in zone/embperl.cpp.
	MESSAGE(STATUS "Using portable Strawberry Perl 5.24 for MSVC linking")

	IF(NOT EXISTS ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_ZIP})
		EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E make_directory ${PROJECT_SOURCE_DIR}/perl)
		EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E make_directory ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_DIR})

		SET(EQEMU_PERL_URLS "${EQEMU_PERL_URL}")
		STRING(REPLACE "http://" "https://" EQEMU_PERL_URL_HTTPS "${EQEMU_PERL_URL}")
		IF(NOT EQEMU_PERL_URL_HTTPS STREQUAL EQEMU_PERL_URL)
			SET(EQEMU_PERL_URLS "${EQEMU_PERL_URL_HTTPS};${EQEMU_PERL_URL}")
		ENDIF()

		SET(PERL_DOWNLOAD_OK FALSE)
		FOREACH(PERL_TRY_URL ${EQEMU_PERL_URLS})
			MESSAGE(STATUS "Downloading portable perl from ${PERL_TRY_URL}")
			FILE(DOWNLOAD ${PERL_TRY_URL} ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_ZIP}
				SHOW_PROGRESS
				STATUS DOWNLOAD_STATUS)
			LIST(GET DOWNLOAD_STATUS 0 STATUS_CODE)
			IF(STATUS_CODE EQUAL 0)
				SET(PERL_DOWNLOAD_OK TRUE)
				BREAK()
			ENDIF()
			MESSAGE(STATUS "Download failed from ${PERL_TRY_URL} (status ${STATUS_CODE})")
			FILE(REMOVE ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_ZIP})
		ENDFOREACH()

		IF(NOT PERL_DOWNLOAD_OK)
			MESSAGE(FATAL_ERROR "Was unable to download portable Perl from ${EQEMU_PERL_URL}")
		ENDIF()

		MESSAGE(STATUS "Extracting files...")
		EXECUTE_PROCESS(
			COMMAND ${CMAKE_COMMAND} -E tar xzf ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_ZIP}
			WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_DIR}
		)
	ENDIF()

	SET(PERL_EXECUTABLE ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_DIR}/perl/bin/perl.exe CACHE FILEPATH "Path to perl program" FORCE)
	SET(PERL_INCLUDE_PATH ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_DIR}/perl/lib/CORE CACHE PATH "Path to perl include files" FORCE)
	SET(PERL_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_DIR}/perl/lib/CORE CACHE PATH "Path to perl include files" FORCE)
	SET(PERL_LIBRARY ${PROJECT_SOURCE_DIR}/perl/${EQEMU_PERL_DIR}/perl/lib/CORE/libperl524.a CACHE FILEPATH "Path to perl library" FORCE)
	MESSAGE(STATUS "MSVC portable Perl: ${PERL_EXECUTABLE}")
	MESSAGE(STATUS "MSVC portable Perl library: ${PERL_LIBRARY}")
ENDIF()